config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :groups
  root to: 'pages#home'
  mount Attachinary::Engine => "/attachinary"
  get "profiles/:id", to: 'profiles#show', as: 'profile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :groups do
    get 'dashboard', to: 'dashboards#display'
    get 'playlist', to: 'dashboards#new_playlist'
    post 'playlist', to: 'dashboards#add_playlist'
    resources :group_users, only: [:create]
    resources :messages, only: [:create]
  end

 resources :studios, only: [:index, :show, :new, :create] do
  resources :slots, only: [:new, :create]
end
  get '/users/auth/spotify/callback', to: 'users#spotify'
  get 'appointment/studios', to: 'appointments#studios'
  get 'appointment/studios/:id', to: 'appointments#slots', as: 'appointment_studio'
  get 'filtered_groups', to: 'groups#filtered_index', as: 'filtered_groups'

  get '/my_groups', to: 'profiles#my_groups'
  get '/my_profile', to: 'profiles#my_profile'

  get '/concept', to: 'pages#concept', as: 'concept'
  get '/features', to: 'pages#features', as: 'features'
  get '/pricing', to: 'pages#pricing', as: 'pricing'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  has_many :studio_equipments
  has_many :studios, through: :studio_equipments

  validates :name, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  has_one :slot, dependent: :nullify
  has_one :studio, through: :slot

  has_attachment :photo

  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users

  has_many :instruments, through: :group_users

  has_many :messages, dependent: :destroy

  belongs_to :admin, class_name: "User"

  validates :name, presence: true
  validates :description, presence: true
  validates :genre, inclusion: { in: %w(rock jazz punk acoustic indie hip-hop classical funk reggae blues metal other) }
  validates :level, inclusion: { in: %w(beginner intermediate advanced) }
  validates :slot, presence: true

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
  belongs_to :instrument

  validates :instrument_id, presence: true
  validates :user, uniqueness: { scope: :group }
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  has_many :user_instruments
  has_many :users, through: :user_instruments

  has_many :group_users
  has_many :groups, through: :group_users

  validates :name, presence: true, uniqueness: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :content, presence: true
  validates :time, presence: true
  validates :user_id, presence: true
  validates :group_id, presence: true

  def minutes_ago
    ((Time.now - self.time) / 60).to_i
  end

end

app/models/slot.rb
class Slot < ApplicationRecord
  belongs_to :studio

  belongs_to :group

  validates :date, presence: true
  validates :start_time, presence: true, if: :before_end_time?
  validates :end_time, presence: true
  validates :taken, inclusion: { in: [true, false] }

  def taken?
    self.taken
  end

  def before_end_time?
    start_time < end_time
  end
end

app/models/studio.rb
class Studio < ApplicationRecord
  has_many :slots, dependent: :destroy
  has_many :groups, through: :slots

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  has_attachments :photos, maximum: 5

  has_many :studio_equipments, dependent: :destroy
  has_many :equipments, through: :studio_equipments

  validates :name, presence: true
  validates :address, presence: true
  validates :price, presence: true
end

app/models/studio_equipment.rb
class StudioEquipment < ApplicationRecord
  belongs_to :studio
  belongs_to :equipment
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_instruments, dependent: :destroy
  has_many :instruments, through: :user_instruments

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook, :spotify]

  has_attachment :photo

  has_many :messages, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users

  def self.find_for_facebook_oauth(auth)
    user_params = auth.to_h.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

end

app/models/user_instrument.rb
class UserInstrument < ApplicationRecord
  belongs_to :instrument
  belongs_to :user
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper

  def generate_profile_picture(user, classes)
    if user.facebook_picture_url
      image_tag user.facebook_picture_url, class: classes.join(" ")
    else
      cl_image_tag user.photo.path, class: classes.join(" ")
    end
  end

end

app/helpers/designs_helper.rb
module DesignsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/slots_helper.rb
module SlotsHelper
end

app/helpers/studios_helper.rb
module StudiosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Band On</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" />
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= favicon_link_tag  'band-on-icon.png' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
  <%= yield %>

    <%= render 'shared/footer' %>

  <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>

  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>
  <%= javascript_include_tag 'application' %>
  <%= cloudinary_js_config %>

  <%= yield(:after_js) %>
</body>
</html>

app/views/pages/concept.html.erb
<br>
<div class="bg-white">
<div class="container">
<h1 class="text-center">Welcome to BandOn</h1>
<h2 class="text-center">The place where you find fellow Jam'ers</h2>
<br>
<br>
<h4 class="text-center content">
BandOn - the meetingplace for music lovers seeking band members to jam with, in studios located near by you.</h4>
<br>
<h4 class="text-center content">Imagine you are 2 or 3 people each playing a different instrument, but missing that 4th person who plays the drums or the percussion, where do you find him or her to form a group and where do you practice?</h4>
<br>
<h4 class="text-center content">BandOn delivers instant access to music players and lovers to join your group making it complete or otherwise just for at good time and opportunity to meet new people, at the push of a few buttons.</h4>
<br>
<h4 class="text-center content">You have access to profile views and available studios near in the city you are staying in, making it possible to find great people to jam with where you live and on the go.</h4>
<br>
<h4 class="text-center content">Go check it out - it ROCKS!</h4>
<br>
<br>
<br>
</div>
</div>

app/views/pages/features.html.erb
<br>
<div class="bg-white">
<div class="container">
<h1 class="text-center">Features</h1>
<h2 class="text-center">So what are you getting?</h2>
<br>
<br>
<h4 class="text-center content">
Easy access to thousands of music players and lovers, waiting to join a band and have a kick a** JAM!</h4>
<br>
<h4 class="text-center content">Easy access to hundreds of available studios near you for you to host a Jam, practice or even a studio recording at the click of a button</h4>
<br>
<h4 class="text-center content">Overview of your jams, practice sessions always keeping you sharp and music resumé up to date</h4>
<br>
<h4 class="text-center content">Meet people all over the people with a mutual interest and passion for Jaming away!</h4>
<br>
<h4 class="text-center content">Go check it out - it ROCKS!</h4>
<br>
<br>
<br>
</div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= asset_path 'bg2.png' %>)";>

  <div class="banner-content">
    <h1>Come play with BandOn</h1>
    <h2>Find your next Jam Session  </h2>

    <div class="section group">
    <%= form_tag(filtered_groups_path, method: :get) do %>

     <div class="col span_1_of_5">
       <div class="form-group">
        <label for="city">City:</label>
        <select class="form-control" id="city" name="city">
          <option value="">All</option>
          <option value="Copenhagen">Copenhagen</option>
          <option value="Paris">Paris</option>
          <option value="Hong Kong">Hong Kong</option>
        </select>
      </div>
    </div>

    <div class="col span_2_of_5">
      <label for="sel1">From:</label>
      <div class="form-group">
        <div class="input-group date">
          <input type="text" class="form-control" name="start-date">
          <div class="input-group-addon">
            <span class="glyphicon glyphicon-th"></span>
          </div>
        </div>
      </div>

    </div>
    <div class="col span_3_of_5">
      <label for="sel1">To:</label>
        <div class="input-group date">
          <input type="text" class="form-control" name="end-date"><span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
        </div>
    </div>

    <div class="col span_4_of_5">
     <div class="form-group">
       <label for="sel1">Genre:</label>
       <select class="form-control" id="sel1" name="genre">
        <option value="">All</option>
        <option>Rock</option>
        <option>Jazz</option>
        <option>Indie</option>
      </select>
    </div>
  </div>

  <div class="col span_5_of_5">
   <input type="submit" class="btn btn-primary btn-lg-round" value="Search"></input>
   <% end %>
 </div>

</div>

<div>

</div>
</div>
</div>

<div class="section-city">
  <hr class="style-one">
  <div class="container">
    <div class="row">

     <div class="col-lg-3 col-md-4 col-xs-6 thumb">
       <div class="card" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.6) 0%, rgba(100,100,100,0.6) 50%), url(<%= asset_path 'barcelona.jpg' %>);">
         <div class="card-description">Barcelona
          <h3>Latin Tunes</h3>
          <h4>Find your next Jam!</h4>
        </div>
        <a class="card-link" href="#" ></a>
      </div>
    </div>

    <div class="col-lg-3 col-md-4 col-xs-6 thumb">
      <div class="card" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.6) 0%, rgba(100,100,100,0.6) 50%), url(<%= asset_path 'blog1.jpg' %>);">
        <div class="card-description">The Blog!
          <h3>News etc.</h3>
          <h4>Listen to the grapewine!</h4>
        </div>
        <a class="card-link" href="#" ></a>

      </div>
    </div>
    <div class="col-lg-3 col-md-4 col-xs-6 thumb">
      <div class="card" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.6) 0%, rgba(100,100,100,0.6) 50%), url(<%= asset_path 'paris.jpg' %>);">
        <div class="card-description">Le Páris!
          <h3>Music lovers</h3>
          <h4>Join the french locals!</h4>
        </div>
        <%= link_to "", groups_path(city: 'paris'), class: 'card-link' %>

      </div>
    </div>
    <div class="col-lg-3 col-md-4 col-xs-6 thumb">
      <div class="card" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.6) 0%, rgba(100,100,100,0.6) 50%), url(<%= asset_path 'jam1.jpg' %>);">
        <div class="card-description">Studio Jam!
          <h3>Jam with others</h3>
          <h4>Find out how it works</h4>
        </div>
        <a class="card-link" href="#" ></a>

      </div>
    </div>
    <div class="col-lg-3 col-md-4 col-xs-6 thumb">
      <div class="card" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.6) 0%, rgba(100,100,100,0.6) 50%), url(<%= asset_path 'hong-kong2.jpg' %>); background-position: center;">
        <div class="card-description">Pearl of Orient
          <h3>Hong Kong</h3>
          <h4>Fix of East-West fusion</h4>
        </div>
        <%= link_to "", groups_path(city: 'hong kong'), class: 'card-link' %>

      </div>

    </div>
    <div class="col-lg-3 col-md-4 col-xs-6 thumb">
      <div class="card" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.6) 0%, rgba(100,100,100,0.6) 50%), url(<%= asset_path 'cph.jpg' %>);">
        <div class="card-description">Wonderful Copenhagen
          <h3>New Nordic</h3>
          <h4>Join the nordic scene!</h4>
        </div>
        <%= link_to "", groups_path(city: 'copenhagen'), class: 'card-link' %>
      </div>

    </div>
    <div class="col-lg-3 col-md-4 col-xs-6 thumb">
      <div class="card" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.6) 0%, rgba(100,100,100,0.6) 50%), url(<%= asset_path 'beats1.jpg' %>);">
        <div class="card-description">Studio Recording!
          <h3>Recording artist?</h3>
          <h4>Get more information</h4>
        </div>
        <a class="card-link" href="#" ></a>

      </div>
    </div>
    <div class="col-lg-3 col-md-4 col-xs-6 thumb">
      <div class="card" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.6) 0%, rgba(100,100,100,0.6) 50%), url(<%= asset_path 'la.jpg' %>);">
        <div class="card-description">City of Angels.
          <h3>Music Capitol</h3>
          <h4>Get your Jam on in LA</h4>
        </div>
        <a class="card-link" href="#" ></a>

      </div>
    </div>
  </div>
</div>

</div>
</div>

app/views/pages/pricing.html.erb
<br>
<div class="bg-white">
<div class="container">
<h1 class="text-center">Pricing</h1>
<h2 class="text-center">So what are the price of all this good stuff?</h2>
<br>
<h4 class="text-center content">
ABSOLUTELY NOTHING! It is totally free for you to enjoy at you disposal!</h4>
<br>
<h4 class="text-center content">However we reserve the right to expose you to ads throughout the site, advertising for instruments, events, manufactures and such alike</h4>
<br>
<h4 class="text-center content">We hope you are good with that (you have to be, you don't have a choice) - you might actually see something you like!</h4>
<br>
<h4 class="text-center content">Now what are you waiting for? - jump in and check it out, it ROCKS!</h4>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <br>
  <hr class="style-two">

  <div class="text-center center-block">
    <a href="https://www.facebook.com/bootsnipp"><i id="social-fb" class="fa fa-facebook-square fa-3x social"></i></a>
    <a href="https://twitter.com/bootsnipp"><i id="social-tw" class="fa fa-twitter-square fa-3x social"></i></a>
    <a href="https://plus.google.com/+Bootsnipp-page"><i id="social-gp" class="fa fa-google-plus-square fa-3x social"></i></a>
    <a href="mailto:bootsnipp@gmail.com"><i id="social-em" class="fa fa-envelope-square fa-3x social"></i></a>
  </div>
  <p class="text-center footertext">Copyright 2016 @ BandOn | Design by Thibault, Sau and Soren</p>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-fixed">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "logo2.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <ul class="nav navbar-nav">
      <li class="nav-item active">
        <%= link_to t(".sign_in", default: "Home"), root_path, class: "navbar-wagon-item navbar-wagon-link" %>
      </li>
      <li class="nav-item">
        <%= link_to t(".sign_in", default: "Concept"), concept_path, class: "navbar-wagon-item navbar-wagon-link" %>
      </li>
      <li class="nav-item">
        <%= link_to t(".sign_in", default: "Features"), features_path, class: "navbar-wagon-item navbar-wagon-link" %>
      </li>
      <li class="nav-item">
        <%= link_to t(".sign_in", default: "Pricing"), pricing_path, class: "navbar-wagon-item navbar-wagon-link" %>
      </li>
    </ul>
  </nav>


  <!-- Different navigation if login or not -->
  <% if user_signed_in? %>



  <!-- Profile picture and dropdown -->
  <div class="navbar-wagon-item">
    <div class="dropdown">
      <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
      <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to appointment_studios_path do %>
          <i class="fa fa-plus-circle"></i> <%= t(".profile", default: "Create new group") %>
          <% end %>
        </li>
        <li>
          <%= link_to my_profile_path do %>
          <i class="fa fa-user"></i> <%= t(".profile", default: "My Profile") %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>

  <% else %>

  <!-- Button (call-to-action) -->
  <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
    <% end %>
</div>

<!-- Dropdown list appearing on mobile only -->
<div class="navbar-wagon-item hidden-md hidden-lg">
  <div class="dropdown">
    <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
    <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
      <li><a href="#">Some mobile link</a></li>
      <li><a href="#">Other one</a></li>
      <li><a href="#">Other one</a></li>
    </ul>
  </div>
</div>
</div>

app/views/shared/tobeused.html.erb
<%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>


<nav class="navbar navbar-light bg-faded  ">
  <ul class="nav navbar-nav">
    <li class="nav-item active">
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Features</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Pricing</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">About</a>
    </li>
  </ul>
</nav>


<!-- Search form -->
<form action="" class="navbar-wagon-search">
  <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
  <button type="submit" class="navbar-wagon-search-btn">
    <i class="fa fa-search"></i>
  </button>
</form>


<!-- Button (call-to-action) -->
<%= link_to t(".top_call_to_action", default: "Login"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>

<!-- Login text link -->
<%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

<!-- navbar copied in -->

<nav class="navbar navbar-light bg-faded  ">


  <!-- from user / show.html.erb -->
  <% @group.users.each do |member| %>
  <div class="member-tag">
    <%= image_tag member.facebook_picture_url || 'http://lorempixel.com/70/70/people', class: "avatar-large" %>
    <p> <%= "#{member.name || member.first_name}" %> </p>
  </div>
  <% end %>
</div>
</div>



<div class="band-members">
  <div class="section-title">
    <p>The band</p>
    <hr>
  </div>
  <div class="member-list">
    <div class="member-tag">
      <%= image_tag @users.admin.facebook_picture_url || 'http://lorempixel.com/70/70/people', class: "avatar-large" %>
      <p> <%= "#{@group.admin.name || @group.admin.first_name}" %> </p>
    </div>

    <div class="studio-summary">
      <div class="section-title">
        <p>The studio</p>
        <hr>
      </div>
      <div class="studio-content">''
        <p> Address: <%= @group.studio.address %></p>
      </div>
    </div>


    <div class="row">
      <div class="col-xs-8">
        <div class="group-summary">
          <% if @facebook_picture_url? %>
          <%= cl_image_tag @facebook_picture_url.path, class: 'polaroid-image' %>
          <% end %>
          <p> <%= "User description: #{@users.description}" %> </p>
        </div>
      </div>



      <div class="col-xs-4">
        <h1>Join Group</h1>
        <%= simple_form_for [ @group, @group_user ] do |f| %>
        <%= f.input :instrument_id, collection: Instrument.all, prompt: "Select your instrument" %>
        <%= f.submit "Join group", class: "btn btn-primary btn-submit" %>
        <% end %>

        <div class="bg-group-show">
          <div class="container">
            <div class="row">
              <div class="col-xs-10 col-xs-offset-1">
                <div class="grey-bkg-box">
                  <div class="group-title text-center">
                    <%= @users.name %>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>


    <!-- profile css. -->

    .grey-bkg-box {
    background-color: rgba(255,255,255,0.7);
    padding: 20px 20px;
    margin-top: 50px;

  }
  .group-title {
  font-size: 25px;
  text-transform: uppercase;
  font-family: 'Exo 2', sans-serif;
  letter-spacing: 3px;
}
.group-summary{
display: flex;
margin-left: -40px;
margin-top: 20px;
}
.polaroid-image{
height: 300px;
width: 250px;
object-fit: cover;
background: white;
display: inline;
float: left;
margin: 0 15px 30px;
padding: 10px 10px 25px;
text-align: center;
text-decoration: none;
-webkit-box-shadow: 0 4px 6px rgba(0, 0, 0, .3);
-moz-box-shadow: 0 4px 6px rgba(0,0,0,.3);
box-shadow: 0 4px 6px rgba(0,0,0,.3);
-webkit-transform: rotate(-4deg);
-moz-transform: rotate(-4deg);
transform: rotate(-4deg);
}
.band-members{
width: 70%;
margin-bottom: 20px;
}
.section-title {
font-size: 18px;
text-transform: uppercase;

hr {
margin-top: 10px;
}
}
.member-list{
display: flex;
}
.member-tag{
text-align: center;
margin-right: 15px;
}
.studio-info{
width: 70%;
}


<div class="col-xs-4">
  <div class="polaroid-image join-group">
    <%= image_tag 'http://www.clker.com/cliparts/B/V/P/X/Z/e/thumbtack-pushpin-2-th.png', class: 'thumb-tack' %>
    <h1>Join Group</h1>
    <br>
    <%= simple_form_for [ @group, @group_user ] do |f| %>
    <%= f.input :instrument_id, collection: Instrument.all, prompt: "Select your instrument", label: "Which instrument would you like to play?" %>
    <%= f.submit "Join group", class: "btn btn-primary btn-submit" %>
    <% end %>
  </div>
</div>
</div>


<div class="row">
  <div class="col-xs-6">
    <%= image_tag @group.studio.photo || 'drums.jpg', class: 'studio-photo'%>
  </div>

  <div class="col-xs-6">
    <div class="studio-description">
      <strong> <%= @user.studio.name %> </strong>
      <br>
      <i class="fa fa-star" aria-hidden="true"></i>
      <i class="fa fa-star" aria-hidden="true"></i>
      <i class="fa fa-star" aria-hidden="true"></i>
      <i class="fa fa-star" aria-hidden="true"></i>
      <i class="fa fa-star-half" aria-hidden="true"></i>

      <br>
      <br>
      <strong> Address </strong>
      <p> <%= @group.studio.address %></p>
    </div>
  </div>

           <div class="col-xs-12">

                  <div id="map" style="width: 100%; height: 300px; position: static; margin-top: 20px;"></div>

                  <% content_for(:after_js) do %>
                  <%= javascript_tag do %>
                  $(document).ready(function() {
                  var handler = Gmaps.build('Google');
                  var styles = <%= render 'studios/mapstyle'%>;
                  handler.buildMap({
                  provider: {
                  styles: styles
                },
                internal: { id: 'map' } }, function() {
                markers = handler.addMarkers(<%= raw @hash.to_json %>);
                handler.bounds.extendWith(markers);
                handler.fitMapToBounds();
                if (markers.length == 0) {
                handler.getMap().setZoom(2);
              } else if (markers.length == 1) {
              handler.getMap().setZoom(14);
            }
          });
        });
        <% end %>
        <% end %>
      </div>