config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :groups
  root to: 'pages#home'
  mount Attachinary::Engine => "/attachinary"
  get "profiles/:id", to: 'profiles#show', as: 'profile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :groups do
    get 'dashboard', to: 'dashboards#display'
    get 'playlist', to: 'dashboards#new_playlist'
    post 'playlist', to: 'dashboards#add_playlist'
    resources :group_users, only: [:create]
    resources :messages, only: [:create]
  end

 resources :studios, only: [:index, :show, :new, :create] do
  resources :slots, only: [:new, :create]
end
  get '/users/auth/spotify/callback', to: 'users#spotify'
  get 'appointment/studios', to: 'appointments#studios'
  get 'appointment/studios/:id', to: 'appointments#slots', as: 'appointment_studio'
  get 'filtered_groups', to: 'groups#filtered_index', as: 'filtered_groups'

  get '/my_groups', to: 'profiles#my_groups'
  get '/my_profile', to: 'profiles#my_profile'

  get '/concept', to: 'pages#concept', as: 'concept'
  get '/features', to: 'pages#features', as: 'features'
  get '/pricing', to: 'pages#pricing', as: 'pricing'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  has_many :studio_equipments
  has_many :studios, through: :studio_equipments

  validates :name, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  has_one :slot, dependent: :nullify
  has_one :studio, through: :slot

  has_attachment :photo

  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users

  has_many :instruments, through: :group_users

  has_many :messages, dependent: :destroy

  belongs_to :admin, class_name: "User"

  validates :name, presence: true
  validates :description, presence: true
  validates :genre, inclusion: { in: %w(rock jazz punk acoustic indie hip-hop classical funk reggae blues metal other) }
  validates :level, inclusion: { in: %w(beginner intermediate advanced) }
  validates :slot, presence: true

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
  belongs_to :instrument

  validates :instrument_id, presence: true
  validates :user, uniqueness: { scope: :group }
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  has_many :user_instruments
  has_many :users, through: :user_instruments

  has_many :group_users
  has_many :groups, through: :group_users

  validates :name, presence: true, uniqueness: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :content, presence: true
  validates :time, presence: true
  validates :user_id, presence: true
  validates :group_id, presence: true

  def minutes_ago
    ((Time.now - self.time) / 60).to_i
  end

end

app/models/slot.rb
class Slot < ApplicationRecord
  belongs_to :studio

  belongs_to :group

  validates :date, presence: true
  validates :start_time, presence: true, if: :before_end_time?
  validates :end_time, presence: true
  validates :taken, inclusion: { in: [true, false] }

  def taken?
    self.taken
  end

  def before_end_time?
    start_time < end_time
  end
end

app/models/studio.rb
class Studio < ApplicationRecord
  has_many :slots, dependent: :destroy
  has_many :groups, through: :slots

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  has_attachments :photos, maximum: 5

  has_many :studio_equipments, dependent: :destroy
  has_many :equipments, through: :studio_equipments

  validates :name, presence: true
  validates :address, presence: true
  validates :price, presence: true
end

app/models/studio_equipment.rb
class StudioEquipment < ApplicationRecord
  belongs_to :studio
  belongs_to :equipment
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_instruments, dependent: :destroy
  has_many :instruments, through: :user_instruments

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook, :spotify]

  has_attachment :photo

  has_many :messages, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users

  def self.find_for_facebook_oauth(auth)
    user_params = auth.to_h.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

end

app/models/user_instrument.rb
class UserInstrument < ApplicationRecord
  belongs_to :instrument
  belongs_to :user
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  before_action :set_group, only: [ :display, :new_playlist, :add_playlist ]

  def display
    @message = Message.new
    authorize @group
    @group_admin = @group.admin
    @group_members = @group.users.reject {|user| user == @group.admin}
    @hash = Gmaps4rails.build_markers(@group.studio) do |studio, marker|
      marker.lat studio.latitude
      marker.lng studio.longitude
    end
  end

  def new_playlist
    spotify_user = RSpotify::User.find(current_user.spotify_id)
    @playlists = spotify_user.playlists
    authorize @group
  end

  def add_playlist
    @group.playlist_name = params[:playlist_name]
    @group.playlist_path = params[:playlist_path]
    @group.save
    authorize @group
    redirect_to group_dashboard_path(@group)
  end

    private

    def set_group
      @group = Group.find(params[:group_id])
    end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper

  def generate_profile_picture(user, classes)
    if user.facebook_picture_url
      image_tag user.facebook_picture_url, class: classes.join(" ")
    else
      cl_image_tag user.photo.path, class: classes.join(" ")
    end
  end

end

app/helpers/designs_helper.rb
module DesignsHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/slots_helper.rb
module SlotsHelper
end

app/helpers/studios_helper.rb
module StudiosHelper
end

app/views/dashboards/display.html.erb
<div class="bg-dashboard">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="dashboard-box" id="title-box">
          <% if @group.photo? %>
          <%= cl_image_tag @group.photo.path, id: 'group-image'%>
          <% end %>
          <div id='group-content'>
            <h1><%= @group.name %> </h1>
            <p> <%= "#{@group.description}" %> </p>
          </div>
          <div id='admin-controls'>
            <% if policy(@group).update? %>
            <%= link_to edit_group_path(@group) do %>
            <i class="fa fa-pencil"></i>
            <% end %>
            <%= link_to group_path(@group), method: :delete do %>
            <i class="fa fa-trash"></i>
            <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="dashboard-box">

          <div class="box-title">
            The band
            <hr>
          </div>

          <div class="member-card">
          <%= link_to generate_profile_picture(@group_admin,  ["avatar-large"]), profile_path(@group_admin)  %>
            <div class="member-card-content">
              <div id="admin-tag"> admin </div>
              <h4> <%= "#{@group_admin.name || @group_admin.first_name}" %> </h4>
              <p> On the <%= GroupUser.where(user: @group_admin).where(group: @group)[0].instrument.name || "..."  %></p>
            </div>
          </div>

          <% @group_members.each do |member| %>
          <div class="member-card">
          <%= link_to generate_profile_picture(member,  ["avatar-large"]), profile_path(member)  %>
            <div class="member-card-content">
              <h4> <%= "#{member.name || member.first_name}" %> </h4>
              <p> On the <%= GroupUser.where(user: member).where(group: @group)[0].instrument.name %></p>
            </div>
          </div>
          <% end %>
        </div>

        <div class="dashboard-box">
         <div class="box-title">
           The studio
           <hr>
         </div>

         <div class="studio-description">
           <strong> <%= @group.studio.name %> </strong>
           <br>
           <i class="fa fa-star" aria-hidden="true"></i>
           <i class="fa fa-star" aria-hidden="true"></i>
           <i class="fa fa-star" aria-hidden="true"></i>
           <i class="fa fa-star" aria-hidden="true"></i>
           <i class="fa fa-star-half" aria-hidden="true"></i>

           <br>
           <br>
               <%= render 'studios/photo_slides', studio: @group.studio%>
            <br>
            <br>
           <strong> Address </strong>
           <p> <%= @group.studio.address %></p>
         </div>
         <div id="map" style="width: 100%; height: 100px; position: static; margin-top: 20px;"></div>

         <% content_for(:after_js) do %>
         <%= javascript_tag do %>
         $(document).ready(function() {
         var handler = Gmaps.build('Google');
         var styles = <%= render 'studios/mapstyle'%>;
         handler.buildMap({
         provider: {
         styles: styles
       },
       internal: { id: 'map' } }, function() {
       markers = handler.addMarkers(<%= raw @hash.to_json %>);
       handler.bounds.extendWith(markers);
       handler.fitMapToBounds();
       if (markers.length == 0) {
       handler.getMap().setZoom(2);
     } else if (markers.length == 1) {
     handler.getMap().setZoom(14);
   }
 });
});
<% end %>
<% end %>
</div>

</div>

<div class="col-xs-6">

  <div class="row">
    <div class="col-xs-12">
      <div class="dashboard-box">
        <div class="box-title">
          Message board
          <hr>
        </div>
        <div id="messages">
          <% if @group.messages.blank? %>
          <p id="first_message"> Be the first to leave a message </p>
          <% else %>
          <% @group.messages.each do |message| %>
          <%= render 'messages/show', message: message %>
          <% end %>
          <% end %>
        </div>
        <%= render 'messages/form', group: @group, message: @message %>
      </div>
    </div>

    <div class="col-xs-12">
      <div class="dashboard-box">
       <div class="box-title">
        Jam playlist
        <hr>
      </div>

     <% if @group.playlist_name %>
       <iframe src="https://embed.spotify.com/?uri=<%= @group.playlist_path %>" width="100%" height="380" frameborder="0" allowtransparency="true"></iframe>

      <% elsif @group.admin == current_user && current_user.spotify_id %>
        <%= link_to "Create a playlist", group_playlist_path(@group)%>
      <% elsif @group.admin == current_user %>
        <%= link_to 'Sign in with Spotify', user_spotify_omniauth_authorize_path %>
      <% else %>
       <p> <%= "Ask the group admin to add a spotify playlist" %></p>
      <% end %>

    </div>
  </div>
</div>
</div>
</div>
</div>
<br>
<br>
</div>

app/views/dashboards/index.html.erb
<div class="container">
  <div class="row">

    <div class="col-xs-6">
      <h1>Group details</h1>
      <h3> <%= @group.name %> </h3>
      <% if @group.photo? %>
        <%= cl_image_tag @group.photo.path, width: 200, height: 300, crop: :fill %>
      <% end %>
      <p> <%= "Group admin: #{@group.admin.name}" %> </p>
      <p> <%= "Group description: #{@group.description}" %> </p>
      <p> Group members:
        <% @group.users.each do |member| %>
        <%= "#{member.name} |" %>
        <% end %>
      </p>
    </div>

    <div class="col-xs-6">

    <div class="row">
      <div class="col-xs-12">
      <h1>Group message board</h1>
      <div id="messages">
        <% if @group.messages.blank? %>
          <p id="first_message"> Be the first to leave a message </p>
        <% else %>
          <% @group.messages.each do |message| %>
            <%= render 'messages/show', message: message %>
          <% end %>
        <% end %>
      </div>
      <%= render 'messages/form', group: @group, message: @message %>
    </div>

    <div class="col-xs-12">
      <h1>Group playlist</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi debitis quam officia deleniti impedit iure adipisci numquam porro quis sapiente aspernatur saepe nemo, quibusdam, ex, nam! Asperiores pariatur aliquid illum.</p>
    </div>
</div>
    </div>
  </div>
</div>

app/views/dashboards/new_playlist.html.erb
<h1 class="page-header">Choose your playlist </h1>

<div class="container">
  <div class="row">
    <% @playlists.each do |playlist|%>

      <div class="form-group col-xs-4">
        <%= form_tag group_playlist_path(@group) , method: "post" do %>
            <h3><%= playlist.name %></h3>
            <%= hidden_field_tag(:playlist_name, playlist.name) %>
            <%= hidden_field_tag(:playlist_path, playlist.uri) %>
        <%= submit_tag "Add this PLaylist", class: "btn btn-primary" %>
        <% end %>
      </div>

    <% end %>

  </div>
</div>