config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :groups
  root to: 'pages#home'
  mount Attachinary::Engine => "/attachinary"
  get "profiles/:id", to: 'profiles#show', as: 'profile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :groups do
    get 'dashboard', to: 'dashboards#display'
    get 'playlist', to: 'dashboards#new_playlist'
    post 'playlist', to: 'dashboards#add_playlist'
    resources :group_users, only: [:create]
    resources :messages, only: [:create]
  end

 resources :studios, only: [:index, :show, :new, :create] do
  resources :slots, only: [:new, :create]
end
  get '/users/auth/spotify/callback', to: 'users#spotify'
  get 'appointment/studios', to: 'appointments#studios'
  get 'appointment/studios/:id', to: 'appointments#slots', as: 'appointment_studio'
  get 'filtered_groups', to: 'groups#filtered_index', as: 'filtered_groups'

  get '/my_groups', to: 'profiles#my_groups'
  get '/my_profile', to: 'profiles#my_profile'

  get '/concept', to: 'pages#concept', as: 'concept'
  get '/features', to: 'pages#features', as: 'features'
  get '/pricing', to: 'pages#pricing', as: 'pricing'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  has_many :studio_equipments
  has_many :studios, through: :studio_equipments

  validates :name, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  has_one :slot, dependent: :nullify
  has_one :studio, through: :slot

  has_attachment :photo

  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users

  has_many :instruments, through: :group_users

  has_many :messages, dependent: :destroy

  belongs_to :admin, class_name: "User"

  validates :name, presence: true
  validates :description, presence: true
  validates :genre, inclusion: { in: %w(rock jazz punk acoustic indie hip-hop classical funk reggae blues metal other) }
  validates :level, inclusion: { in: %w(beginner intermediate advanced) }
  validates :slot, presence: true

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
  belongs_to :instrument

  validates :instrument_id, presence: true
  validates :user, uniqueness: { scope: :group }
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  has_many :user_instruments
  has_many :users, through: :user_instruments

  has_many :group_users
  has_many :groups, through: :group_users

  validates :name, presence: true, uniqueness: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :content, presence: true
  validates :time, presence: true
  validates :user_id, presence: true
  validates :group_id, presence: true

  def minutes_ago
    ((Time.now - self.time) / 60).to_i
  end

end

app/models/slot.rb
class Slot < ApplicationRecord
  belongs_to :studio

  belongs_to :group

  validates :date, presence: true
  validates :start_time, presence: true, if: :before_end_time?
  validates :end_time, presence: true
  validates :taken, inclusion: { in: [true, false] }

  def taken?
    self.taken
  end

  def before_end_time?
    start_time < end_time
  end
end

app/models/studio.rb
class Studio < ApplicationRecord
  has_many :slots, dependent: :destroy
  has_many :groups, through: :slots

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  has_attachments :photos, maximum: 5

  has_many :studio_equipments, dependent: :destroy
  has_many :equipments, through: :studio_equipments

  validates :name, presence: true
  validates :address, presence: true
  validates :price, presence: true
end

app/models/studio_equipment.rb
class StudioEquipment < ApplicationRecord
  belongs_to :studio
  belongs_to :equipment
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_instruments, dependent: :destroy
  has_many :instruments, through: :user_instruments

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook, :spotify]

  has_attachment :photo

  has_many :messages, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users

  def self.find_for_facebook_oauth(auth)
    user_params = auth.to_h.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

end

app/models/user_instrument.rb
class UserInstrument < ApplicationRecord
  belongs_to :instrument
  belongs_to :user
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

  def studios
    # @studios = policy_scope(Studio).where.not(latitude: nil, longitude: nil).order(created_at: :desc)
    @studios = policy_scope(Studio).order(created_at: :desc)
    @hash = Gmaps4rails.build_markers(@studios) do |studio, marker|
      marker.lat studio.latitude
      marker.lng studio.longitude
    end
    authorize @studios
  end

  def slots
    @studio = Studio.find(params[:id])
    authorize @studio
    @available_slots = @studio.slots.where(taken: false)
    @studio_coordinates = { lat: @studio.latitude, lng: @studio.longitude }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper

  def generate_profile_picture(user, classes)
    if user.facebook_picture_url
      image_tag user.facebook_picture_url, class: classes.join(" ")
    else
      cl_image_tag user.photo.path, class: classes.join(" ")
    end
  end

end

app/helpers/designs_helper.rb
module DesignsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/slots_helper.rb
module SlotsHelper
end

app/helpers/studios_helper.rb
module StudiosHelper
end

app/views/appointments/_mapstyle.html.erb
[
    {
        "featureType": "administrative",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "poi",
        "stylers": [
            {
                "visibility": "simplified"
            }
        ]
    },
    {
        "featureType": "road",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "simplified"
            }
        ]
    },
    {
        "featureType": "water",
        "stylers": [
            {
                "visibility": "simplified"
            }
        ]
    },
    {
        "featureType": "transit",
        "stylers": [
            {
                "visibility": "simplified"
            }
        ]
    },
    {
        "featureType": "landscape",
        "stylers": [
            {
                "visibility": "simplified"
            }
        ]
    },
    {
        "featureType": "road.highway",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "road.local",
        "stylers": [
            {
                "visibility": "on"
            }
        ]
    },
    {
        "featureType": "road.highway",
        "elementType": "geometry",
        "stylers": [
            {
                "visibility": "on"
            }
        ]
    },
    {
        "featureType": "water",
        "stylers": [
            {
                "color": "#84afa3"
            },
            {
                "lightness": 52
            }
        ]
    },
    {
        "stylers": [
            {
                "saturation": -17
            },
            {
                "gamma": 0.36
            }
        ]
    },
    {
        "featureType": "transit.line",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#3f518c"
            }
        ]
    }
]

app/views/appointments/slots.html.erb
<br>
<br>
<div class="container">
  <div class="row">
    <div class="col-xs-6">

      <div class='section-title' style='font-size: 25px;'>Step 2: Select slot</div>

      <% if @available_slots.blank? %>
      <h4>Sorry no spots available</h4>
      <% else %>
      <% @available_slots.each do |slot| %>
      <ul>

        <li>
          <time class="icon <%="#{slot.date.strftime("%A").downcase}" %>">
            <span class="month"><%="#{slot.date.strftime("%B").downcase}" %></span>
            <span class="day"><%="#{slot.date.strftime("%d").downcase}" %></span>
            <span class="week"><%="#{slot.date.strftime("%A")}" %></span>
          </time>
        </li>
      </ul>
      <p> <%= link_to "#{slot.date.strftime("%A, %d %B %Y")}: #{slot.start_time.strftime("%l:%M %p")} - #{slot.end_time.strftime("%l:%M %p")}", new_group_path(slot_id: slot.id) %> </p>
      <% end %>
      <% end %>





    </div>
  </div>

</div>
</div>

app/views/appointments/studios.html.erb
<br>
<br>
<div class="container">
  <div class="row">
    <div class="col-xs-6">

      <div class='section-title' style='font-size: 25px;'>Step 1: Select studio
      <hr>
      </div>
      <br>

      <% @studios.each do |studio| %>
      <%= link_to "#{studio.name}", appointment_studio_path(studio) %>
      <p> Address: <%= studio.address%> </p>
      <p> Price: $<%= studio.price%>/hr </p>
      <% end %>

    </div>
    <div class = "col-xs-6" style = "background-color: #dedef8;
    box-shadow: inset 1px -1px 1px #444, inset -1px 1px 1px #444;">

    <div id="map" style="width: 100%; height: 600px; position: static"></div>

    <% content_for(:after_js) do %>
    <%= javascript_tag do %>
    $(document).ready(function() {
    var handler = Gmaps.build('Google');
    var styles = <%= render 'mapstyle'%>;
    handler.buildMap({
    provider: {
    styles: styles
  },
  internal: { id: 'map' } }, function() {
  markers = handler.addMarkers(<%= raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  if (markers.length == 0) {
  handler.getMap().setZoom(2);
} else if (markers.length == 1) {
handler.getMap().setZoom(14);
}
});
});
<% end %>
<% end %>
</div>
</div>
</div>